### ISSUE TITLE
Build fails locally

### ISSUE THREAD

**Issue by koddsson** [arnif/sonarr-native#34]
I just check out, install node modules and run `react-native run-ios`.

Is this a error in my setup or is the project broken for ios? I'm running `macOS Sierra 10.12.1 Beta`

```
The following build commands failed:
    CompileC /Users/koddsson/Repos/sonarr-native/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/Sonarr.app
No devices are booted.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/koddsson/Repos/sonarr-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Sonarr.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at _runIOS (/Users/koddsson/Repos/sonarr-native/node_modules/react-native/local-cli/runIOS/runIOS.js:91:34)
    at Promise (/Users/koddsson/Repos/sonarr-native/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5)
    at tryCallTwo (/Users/koddsson/Repos/sonarr-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/koddsson/Repos/sonarr-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/koddsson/Repos/sonarr-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/koddsson/Repos/sonarr-native/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/koddsson/Repos/sonarr-native/node_modules/react-native/local-cli/cliEntry.js:95:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by arnif** [comment]
No this is XCODE 8 issue. I ran into this problem as well after upgrading to Sierra.

https://github.com/facebook/react-native/issues/8584#issuecomment-236366222

This should be solved in react-native v0.33 but I haven't had time to update the project to v0.33.

**Comment by koddsson** [comment]
Gotcha!

**Comment by koddsson** [comment]
I couldn't get this to work at all 😭

**Comment by arnif** [comment]
Same error even after the fix ?

**Comment by arnif** [comment]
#36  was just merged please pull latest master and try again (don't forget `npm install` or just `rm -rf` and start fresh).

**Comment by koddsson** [comment]
Awesome. I'll check that out!

**Comment by koddsson** [comment]
💥 Totally works 💥

**Comment by arnif** [comment]
Sweeeet #22 is waiting for you ;)
